Ensure that we use the johnzon bundle after provider registration have completed
Having the storage-rrd4j bundle on the same startlevel as the other
bundles lead to exceptions such as:

Exception in thread
"nu.muntea.htr.storage.rrd4j.internal.TemperatureRecorder"
javax.json.JsonException: org.apache.johnzon.core.JsonProviderImpl not
found
	at javax.json.spi.JsonProvider.doLoadProvider(JsonProvider.java:118)
	at javax.json.spi.JsonProvider.provider(JsonProvider.java:89)
	at javax.json.Json.createReader(Json.java:88)
	at nu.muntea.htr.storage.rrd4j.internal.SensorsCpuTemperatureReader.readTemperature(SensorsCpuTemperatureReader.java:50)
	at nu.muntea.htr.storage.rrd4j.internal.TemperatureRecorder.lambda$new$0(TemperatureRecorder.java:24)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: Cannot cast
org.apache.johnzon.core.JsonProviderImpl to javax.json.spi.JsonProvider
	at java.lang.Class.cast(Class.java:3369)
	at javax.json.spi.JsonProvider.doLoadProvider(JsonProvider.java:116)
	... 5 more